### ISSUE TITLE
[INFRA] Spring Data JPA로 DB 연결 설정하기

### ISSUE THREAD

**Issue by TProgramer** [PANTS-GOORM/BackEnd#9]
> PostgreSQL(v16.2)에 스프링 서버를 연결하기

- Spring Data JPA를 통해 스프링 서버를 DB에 연결하기
- DB 인증 정보와 같이 민감한 secret 파일이 노출되지 않도록 private 레포에 별도로 관리하고, 이를 submodule로 연동하하기

**Comment by chickennight** [comment]
오타 수정해주세요
